### PR TITLE
updates for jade release

### PR DESCRIPTION
**Pull request by wjwwood**
@dirk-thomas @tfoote @esteve for review

Can someone merge and deploy this for me? My connection is pretty unreliable atm.

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
@esteve this one also says `kame` and not `kinetic`.

**Comment by esteve** [comment]
@wjwwood yeah, better use kinetic, sorry for the too-fast-review.

**Comment by wjwwood** [comment]
Sounds good, updated.

**Comment by dirk-thomas** [comment]
lgtm

**Comment by tfoote** [comment]
lgtm

**Comment by wjwwood** [comment]
Who's in charge of ros browse?

**Pull request merged**
